packages:
  - app
  - ui
catalog:
  '@stream-io/video-react-sdk': ^1.24.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  react: ^19.2.0
  react-aria: ^3.44.0
  react-aria-components: ^1.13.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
onlyBuiltDependencies:
  - esbuild
